{% set name = "python-ldap" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4711cacf013e298754abd70058ccc995758177fb425f1c2d30e71adfc1d00aa5

build:
  number: 1
  skip: true  # [win]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - pyasn1
    - pyasn1-modules
    - openldap
  run:
    - python
    - pyasn1
    - pyasn1-modules
    - openldap

test:
  imports:
    - ldap
    - ldap.controls
    - ldap.extop
    - ldap.schema
    # - slapdtest

about:
  home: https://www.python-ldap.org/
  license: Python Software Foundation
  license_family: OTHER
  license_file: LICENCE
  summary: Python modules for implementing LDAP clients
  doc_url: https://www.python-ldap.org/en/latest/
  dev_url: https://github.com/python-ldap/python-ldap

extra:
  recipe-maintainers:
    - mariusvniekerk
